language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - python ./setup.py install
  - pip install coverage codecov

# command to run tests
script:
  - coverage run ./setup.py test

after_success:
  - codecov

