language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - python ./setup.py install
  - pip install black coverage codecov

# command to run tests
script:
  - black --check ./setup.py ./python_caltrain
  - coverage run ./setup.py test

after_success:
  - codecov

